from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Float, ForeignKey, JSON
)
from sqlalchemy.orm import relationship
from database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    logs = relationship("SymptomLog", back_populates="user", cascade="all, delete-orphan")
    insights = relationship("Insight", back_populates="user", cascade="all, delete-orphan")


class SymptomLog(Base):
    __tablename__ = "symptom_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # Raw free-text from the user
    raw_text = Column(Text, nullable=False)

    # Gemini-extracted structured data:
    # [{"name": "headache", "severity": 7, "location": "frontal", "duration": "2h"}, ...]
    symptoms = Column(JSON, nullable=False, default=list)

    # Overall severity score 1–10 (averaged or highest from extracted symptoms)
    overall_severity = Column(Float, nullable=True)

    logged_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    user = relationship("User", back_populates="logs")


class Insight(Base):
    __tablename__ = "insights"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # "daily" | "pattern"
    insight_type = Column(String, nullable=False, default="daily")

    # Plain-English text generated by Gemini
    content = Column(Text, nullable=False)

    generated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    user = relationship("User", back_populates="insights")
